name: Auto Merge Cursor PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: github.actor == 'cursor[bot]' || startsWith(github.head_ref, 'cursor/')
    runs-on: ubuntu-latest

    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
